repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: []
        args: ["--config-file", "pyproject.toml"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-q", "-r", "my_work_assistant/src", "-x", "my_work_assistant/src/my_work_assistant/tests"]

  - repo: https://github.com/trailofbits/pip-audit
    rev: v2.7.3
    hooks:
      - id: pip-audit
        args: ["-l"]
