[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "copilot-workspace"
version = "0.1.0"
description = "Python utilities for generating the Copilot instructions workspace"
readme = "README.md"
authors = [{name = "Erik Plachta"}]
requires-python = ">=3.9"

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "-ra"
